######################## default configuration ####################
baseURL = "https://arcanaanalytica.com/"
languageCode = "en-us"
title = "Jake Weber's Arcana Analytica"
theme = "icelab-hugo"
summaryLength = "70"


############################## Output ###############################
[outputs]
home = ["HTML", "RSS"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################## Output ###############################
# JS Plugins
[[params.plugins.js]]
URL = "plugins/plugins.js"


############################## navigation ###########################
[[menu.main]]
name = "Biography"
URL = "about"
weight = 2

[[menu.main]]
name = "Portfolio"
URL = "works"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4


#################### default parameters ##############################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Jake Weber's Arcana Analytica"
author = "Jake Weber"
# contact form action
contact_form_action = "https://formspree.io/f/xoqrprle" # contact form works with https://formspree.io
# footer content
footer_content = ""

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDQyd7ZvCPkcLHNK4gZXQDqZdAptjPUcQk"
map_latitude = "33.649765"
map_longitude = "-117.882422"
map_marker = "images/marker.png"

############################# social site ########################
[[params.social]]
name = "linkedin"
icon = "fa-linkedin" # fontawesome icon pack v4.7
link = "https://www.linkedin.com/in/datadruid/"

[[params.social]]
name = "github"
icon = "fa-github" # fontawesome icon pack v4.7
link = "https://github.com/the-data-druid"

[[params.social]]
name = "instagram"
icon = "fa-instagram" # fontawesome icon pack v4.7
link = "https://www.instagram.com/foliage.folk/?hl=en"
